plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.media']
}

application {
    mainClass = 'de.schliweb.moveapiece.desktop.DesktopApp'
}

dependencies {
    implementation project(':core')
    implementation 'com.github.bhlangonijr:chesslib:1.3.7'

    testImplementation 'junit:junit:4.13.2'
}

apply from: 'stockfish.gradle'
apply from: 'packaging.gradle'
